### PR TITLE
Some updates in behaviour to the toolbox

### PR DESCRIPTION
**Pull request by tmhglnd**
Hi! I've been a user of the toolbox for many years and enjoy it very much, but there were always some little "bugs" that did not work so well for me (more a feature because of implementation then an actual bug). I've made some adjustments to improve the toolbox and hopefully you agree with these implementations, or some of them, and like to include them in the main branch. I'll try to explain the differences in implementation below with some screenshots/gifs of *new* (left) and *old* (right, i used Max7 to run them side-by-side, but the results of the previous version was similar in max8) version:

### single to multiple / multiple to single
Instead of sorting by half the distance between lowest and highest object and selecting the most left from the top or bottom half, this implementation searches for the highest (or lowest) object and connects everything to it.

Screen Shot 2021-09-20 at 17 12 02
Screen Shot 2021-09-20 at 17 11 42

### row to single / single to row
The same as above, not sorting by half the distance between lowest and highest object and choosing the most left from the top or bottom half, but searching for the top or bottom object.

Screen Shot 2021-09-20 at 17 11 18
Screen Shot 2021-09-20 at 17 14 08

This behaviour also fixes the "bug" where sometimes the wrong object is selected because it is most to the left.

Screen Shot 2021-09-20 at 17 29 20
Screen Shot 2021-09-20 at 17 28 51

### row to row
For this one I changed the behaviour to sort all objects on the y-axis and split the array in half, if the array is uneven it removes the last object. It then connects one top object to one bottom object etc. The result is all objects are connected, even if they are visual both on the top-half (which was the old behaviour).

Screen Shot 2021-09-20 at 17 12 56

### alignx / aligny
This new implementation uses the distance between the most left or top object and the mouse x/y to stretch/shrink the objects in place, instead of using the mouse movement to displace as a delta value. This gives a bit more control without objects shooting outside the boundaries of the patcher window.

alignx
aligny

### look
The last thing that I changed is the look of the patcher to fit the modern Max version, but this is of course a matter of taste as well. I've also updated the readme file with a screenshot of the current version and shortcuts.

I'm curious to hear what you think of these adjustments. All the best, Timo

### undo

I added a 2d-array which allows you to undo multiple connections made. The undo history is set to 16, but can of course be made larger or smaller in the .js file

### nodeJS

I've changed the toolbox_config.js to a nodeJS version running in [node.script] since I was having issues with the activation and writing of the toolbox_start.maxpat to the `max-startup` folder inside the package contents. The node.script version will check if the folder already exists, if not the folder is created with `fs.mkdirSync()`, then the file is written to the folder. Intead of searching for the max-startup folder via loadmess to [absolutepath], I've now used the C74 folder via [absolutepath], since you can be sure that folder exists.

### CODE REVIEW

**Comment by tmhglnd** [comment]
No worries, let me know what you think.

**Comment by natcl** [comment]
Nice ! Do you consider this stable now   ?
Let me know and I'll have a  look !

**Comment by tmhglnd** [comment]
For me it has been working stable up till now. The only thing I just realized is that, because I made a fix for writing the toolbox start patch to the init folder of the app via `[node.script]`, the toolbox is now only compatible with Max8. So we'll have to consider if older versions are from now on unsupported, or I need to think of a way to have it be backwards compatible. Otherwise you could create a release of the version before the node.script was introduced for the Max7 and older users.

**Comment by tmhglnd** [comment]
I think this is now ready for a first release of the new version :) And if any bugs arise from there I will be happy to help maintain the package. I use Max daily.

**Comment by natcl** [comment]
Let's merge :)

**Comment by natcl** [comment]
Just noticed the changeling is not updated, do you think you can update CHANGELOG.md to reflect the updates ?

Thanks !

**Comment by tmhglnd** [comment]
Yes, done! :) Also changed the version number in the js document, I had it at 17 (don't know why haha). Now it matches

**Pull request merged**
