### PR TITLE
A few updates

### PR DESCRIPTION
**Pull request by tmhglnd**
This update fixes issue #12. Just by single pressing `x` or `y` the objects are auto distributed evenly in that axis. Holding `x` or `y` a bit longer (> 150ms) allows to use the mouse drag to adjust the distance between distribution (as it was working before).

I've also included a few new shortkeys:

`shift-k` - clear the max console
`shift-alt-,` (or `¯` on my keyboard) - open audio status menu
`shift-alt-a` (or `Å` on my keyboard) - turn DSP on/off

### CODE REVIEW

**Comment by tmhglnd** [comment]
Commits from fffac4c fix an issue in Max 8.6+ where the activate state wasn't stored because of some behaviour changes with node.script by Cycling.

**Comment by natcl** [comment]
Oh nice will merge asap, this has all been tested ?

**Comment by tmhglnd** [comment]
Has been tested by me and the other user who pushed some fixes. Besides that not sure, didn't receive any other bug reports or issues so far.

**Comment by natcl** [comment]
Thanks! Will merge!

**Pull request merged**
